# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "k8s.io/api/core/v1",
  "k8s.io/apimachinery/pkg/apis/meta/v1",
]

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/apiextensions"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/k8shealthz"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microerror"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microkit"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/micrologger"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/operatorkit"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.8.5"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.8.5"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.8.5"

[prune]
  go-tests = true
  unused-packages = true
