apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:{{ .Values.port }}'
    service:
      helm:
        http:
          clientTimeout: '{{ .Values.Installation.V1.Helm.HTTP.ClientTimeout }}'
        tillerNamespace:  '{{ .Values.tiller.namespace }}'
      kubernetes:
        incluster: true
        watch:
          namespace: '{{ .Values.namespace }}'
