apiVersion: v2
name: chart-operator
version: 4.3.0
appVersion: 4.3.0
home: https://github.com/giantswarm/chart-operator
description: A Helm chart for the chart-operator
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  io.giantswarm.application.restrictions.cluster-singleton: 'true'
  io.giantswarm.application.restrictions.fixed-namespace: giantswarm
  io.giantswarm.application.restrictions.gpu-instances: 'false'
  io.giantswarm.application.restrictions.namespace-singleton: 'true'
  io.giantswarm.application.team: honeybadger
